import Link from "next/link";
import { notFound } from "next/navigation";
import { updateInspectionAction } from "@/app/actions/quality";
import { getWorkspaceContext, requireUser } from "@/lib/auth";

export const dynamic = "force-dynamic";
export default async function InspectionPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const [{ id }, feedback, { supabase }, { project }] = await Promise.all([params, searchParams, requireUser(), getWorkspaceContext()]);
  const { data: inspection, error } = await supabase.from("inspections").select("id,folio,status,result,notes,started_at,completed_at,segment_id,segments(tag),inspection_template_versions(version,inspection_templates(name,inspection_type))").eq("project_id", project.id).eq("id", id).maybeSingle();
  if (error) throw new Error(error.message); if (!inspection) notFound();
  const template = inspection.inspection_template_versions?.[0]; const definition = template?.inspection_templates?.[0]; const segment = inspection.segments?.[0];
  return <div className="module-page"><section className="page-heading"><div><div className="eyebrow"><span>INSPECCIÓN · {definition?.inspection_type ?? "GENERAL"}</span></div><h1>{inspection.folio}</h1><p>{definition?.name ?? "Inspección"} · Versión {template?.version ?? 1}</p></div>{inspection.segment_id && <Link className="secondary-button" href={`/segments/${inspection.segment_id}`}>Ver tramo {segment?.tag}</Link>}</section>{feedback.error && <p className="form-error">{feedback.error}</p>}{feedback.success && <p className="form-success">{feedback.success}</p>}<section className="inspection-editor"><aside><strong>Estado actual</strong><span>{inspection.status}</span><small>Tramo</small><b>{segment?.tag ?? "Sin tramo"}</b><small>Inicio</small><b>{inspection.started_at ? new Date(inspection.started_at).toLocaleString("es-MX") : "Pendiente"}</b></aside><form action={updateInspectionAction} className="auth-form"><input type="hidden" name="inspectionId" value={inspection.id} /><label>Estado<select name="status" defaultValue={inspection.status}><option value="DRAFT">Borrador</option><option value="IN_PROGRESS">En progreso</option><option value="COMPLETED">Completada</option><option value="PENDING_REVIEW">Pendiente de revisión</option><option value="APPROVED">Aprobada</option><option value="REJECTED">Rechazada</option><option value="VOID">Anulada</option></select></label><label>Resultado<select name="result" defaultValue={inspection.result ?? ""}><option value="">Sin resultado</option><option value="ACCEPTED">Aceptado</option><option value="REJECTED">Rechazado</option></select></label><label className="full">Observaciones<textarea name="notes" rows={8} defaultValue={inspection.notes ?? ""} placeholder="Registra alcance, hallazgos, mediciones y pendientes..." /></label><button className="primary-button" type="submit">Guardar inspección y actualizar avance</button></form></section></div>;
}
