"use client";

import { useState, type PointerEvent } from "react";
import { Highlighter, MousePointer2, RotateCcw, Save } from "lucide-react";
import { saveSegmentDrawingMarkupAction } from "@/app/actions/quality";

type Geometry = { type: "rectangle"; x: number; y: number; width: number; height: number };
type Segment = { id: string; tag: string; description: string | null; drawing_geometry: Geometry | null };

export function DrawingMarkup({ drawingId, revisionId, url, segments }: { drawingId: string; revisionId: string; url: string; segments: Segment[] }) {
  const [marking, setMarking] = useState(false); const [selected, setSelected] = useState(segments[0]?.id ?? "");
  const [start, setStart] = useState<{ x: number; y: number } | null>(null); const [geometry, setGeometry] = useState<Geometry | null>(null);
  const point = (event: PointerEvent<HTMLDivElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { x: (event.clientX - rect.left) / rect.width, y: (event.clientY - rect.top) / rect.height }; };
  const begin = (event: PointerEvent<HTMLDivElement>) => { if (!marking) return; event.currentTarget.setPointerCapture(event.pointerId); const value = point(event); setStart(value); setGeometry({ type: "rectangle", ...value, width: 0.001, height: 0.001 }); };
  const move = (event: PointerEvent<HTMLDivElement>) => { if (!start || !marking) return; const end = point(event); setGeometry({ type: "rectangle", x: Math.min(start.x, end.x), y: Math.min(start.y, end.y), width: Math.max(Math.abs(end.x - start.x), .001), height: Math.max(Math.abs(end.y - start.y), .001) }); };
  return <div className="drawing-workspace"><div className="drawing-toolbar"><label>Tramo<select value={selected} onChange={(event) => { setSelected(event.target.value); setGeometry(segments.find((segment) => segment.id === event.target.value)?.drawing_geometry ?? null); }}><option value="">Selecciona un tramo</option>{segments.map((segment) => <option value={segment.id} key={segment.id}>{segment.tag} · {segment.description || "Sin descripción"}</option>)}</select></label><button className={marking ? "primary-button" : "secondary-button"} type="button" onClick={() => setMarking(!marking)}>{marking ? <Highlighter /> : <MousePointer2 />}{marking ? "Arrastra para amarillar" : "Activar marcado"}</button><button className="secondary-button" type="button" onClick={() => setGeometry(null)}><RotateCcw /> Limpiar</button><form action={saveSegmentDrawingMarkupAction}><input type="hidden" name="drawingId" value={drawingId} /><input type="hidden" name="drawingRevisionId" value={revisionId} /><input type="hidden" name="segmentId" value={selected} /><input type="hidden" name="geometry" value={JSON.stringify(geometry)} /><button className="primary-button" disabled={!selected || !geometry}><Save /> Guardar vínculo</button></form></div><div className="drawing-canvas"><iframe src={url} title="Visor del plano PDF" /><div className={`markup-layer ${marking ? "is-marking" : ""}`} onPointerDown={begin} onPointerMove={move} onPointerUp={() => setStart(null)}>{segments.filter((segment) => segment.drawing_geometry && segment.id !== selected).map((segment) => <span className="segment-mark saved" style={{ left: `${segment.drawing_geometry!.x * 100}%`, top: `${segment.drawing_geometry!.y * 100}%`, width: `${segment.drawing_geometry!.width * 100}%`, height: `${segment.drawing_geometry!.height * 100}%` }} title={segment.tag} key={segment.id} />)}{geometry && <span className="segment-mark selected" style={{ left: `${geometry.x * 100}%`, top: `${geometry.y * 100}%`, width: `${geometry.width * 100}%`, height: `${geometry.height * 100}%` }} />}</div></div></div>;
}
