import { createInspectionTemplateAction, updateInspectionTemplateAction } from "@/app/actions/quality";
import { getWorkspaceContext, requireUser } from "@/lib/auth";

export const dynamic = "force-dynamic";
const disciplines = [["MECHANICAL","Mecánica"],["ELECTRICAL","Eléctrica"],["CIVIL","Civil"],["PLC","PLC / Control"],["INSTRUMENTATION","Instrumentación"],["GENERAL","General"]] as const;

export default async function InspectionTemplatesPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const [{ supabase }, { project }, feedback] = await Promise.all([requireUser(), getWorkspaceContext(), searchParams]);
  const { data, error } = await supabase.from("inspection_templates").select("id,code,name,inspection_type,inspection_template_versions(version,status)").eq("project_id", project.id).is("archived_at", null).order("inspection_type").order("name");
  if (error) throw new Error(error.message.includes("project_id") ? "Falta aplicar la migración 005 en Supabase." : error.message);
  return <div className="module-page"><section className="page-heading"><div><div className="eyebrow"><span>{project.code}</span></div><h1>Tipos de inspección</h1><p>Organiza y renombra libremente las revisiones y pruebas aplicables al proyecto.</p></div></section>{feedback.error && <p className="form-error">{feedback.error}</p>}{feedback.success && <p className="form-success">{feedback.success}</p>}<div className="projects-layout"><section className="template-groups">{disciplines.map(([code,label]) => { const templates=(data ?? []).filter((item) => item.inspection_type===code); if(!templates.length) return null; return <section className="template-group" key={code}><h2>{label}</h2>{templates.map((template) => <form action={updateInspectionTemplateAction} className="template-edit-row" key={template.id}><input type="hidden" name="templateId" value={template.id} /><span className="project-code">{template.code.slice(0,2)}</span><label>Nombre<input name="name" required defaultValue={template.name} /></label><label>Categoría<select name="discipline" defaultValue={template.inspection_type}>{disciplines.map(([value,text])=><option value={value} key={value}>{text}</option>)}</select></label><small>{template.code} · v{template.inspection_template_versions[0]?.version ?? 1}</small><button className="secondary-button">Guardar</button></form>)}</section>; })}</section><aside className="create-panel"><h2>Nuevo tipo</h2><p>Ejemplo: Eléctrica → Prueba de continuidad. Más adelante el Form Builder permitirá cargar sus campos.</p><form action={createInspectionTemplateAction} className="auth-form"><label>Código<input name="code" required pattern="[A-Za-z0-9-]+" placeholder="ELEC-CONTINUITY" /></label><label>Nombre<input name="name" required placeholder="Prueba de continuidad" /></label><label>Categoría<select name="discipline">{disciplines.map(([value,text])=><option value={value} key={value}>{text}</option>)}</select></label><button className="primary-button" type="submit">Crear tipo</button></form></aside></div></div>;
}
