import { createInspectionTemplateAction } from "@/app/actions/quality";
import { getWorkspaceContext, requireUser } from "@/lib/auth";

export const dynamic = "force-dynamic";

export default async function InspectionTemplatesPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const [{ supabase }, { project }, feedback] = await Promise.all([requireUser(), getWorkspaceContext(), searchParams]);
  const { data, error } = await supabase.from("inspection_templates").select("id,code,name,inspection_type,inspection_template_versions(version,status)").eq("project_id", project.id).is("archived_at", null).order("inspection_type").order("name");
  if (error) throw new Error(error.message.includes("project_id") ? "Falta aplicar la migración 005 en Supabase." : error.message);
  return <div className="module-page"><section className="page-heading"><div><div className="eyebrow"><span>{project.code}</span></div><h1>Tipos de inspección</h1><p>Catálogo personalizable por proyecto para pruebas mecánicas, civiles, eléctricas y otras disciplinas.</p></div></section>{feedback.error && <p className="form-error">{feedback.error}</p>}{feedback.success && <p className="form-success">{feedback.success}</p>}<div className="projects-layout"><section className="project-list">{data?.map((template) => <article className="project-row" key={template.id}><span className="project-code">{template.code.slice(0, 2)}</span><div><strong>{template.name}</strong><small>{template.code} · {template.inspection_type} · versión {template.inspection_template_versions[0]?.version ?? 1}</small></div><span className="status-pill active">{template.inspection_template_versions[0]?.status ?? "DRAFT"}</span></article>)}</section><aside className="create-panel"><h2>Nuevo tipo</h2><p>Crea el catálogo primero; el constructor de campos permitirá ampliar después el checklist JSON versionado.</p><form action={createInspectionTemplateAction} className="auth-form"><label>Código<input name="code" required pattern="[A-Za-z0-9-]+" placeholder="MECH-VISUAL" /></label><label>Nombre<input name="name" required placeholder="Inspección visual mecánica" /></label><label>Disciplina<select name="discipline"><option value="MECHANICAL">Mecánica</option><option value="CIVIL">Civil</option><option value="ELECTRICAL">Eléctrica</option><option value="INSTRUMENTATION">Instrumentación</option><option value="GENERAL">General</option></select></label><button className="primary-button" type="submit">Crear tipo</button></form></aside></div></div>;
}
